os: linux
dist: trusty
sudo: required
compiler: gcc
language: ruby
rvm:
  - 2.3.3
addons:
  apt:
    packages:
      - build-essential
      - libsdl2-dev
      - libsdl2-ttf-dev
      - libpango1.0-dev
      - libgl1-mesa-dev
      - libopenal-dev
      - libsndfile-dev
before_install:
  - gem install bundler -v 1.14.3
script: rake spec
